## Домашняя работа
Для задач Easy и Normal использовать данные Титаника

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import scipy.stats
from statsmodels.stats.proportion import proportions_ztest

In [18]:
df = pd.read_csv(r'D:\Курсы Питон\Титаник\train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### Easy
Оценить с помощью доверительных интервалов:

выживаемость всех пассажиров (оценить среднее по isSurvived)

выживаемость женщин

выживаемость людей с каютами первого класса

Ответить на вопросы:

Какой вариант оценки доверительных интервалов нужно использовать в данной задаче и почему?

Какая из ошибок более критична для данной задачи - I или II рода?

Для всех пассажиров

In [19]:
mean = df[["Survived"]].mean() #доля выживших - "среднее"
std = df[["Survived"]].std() #стандартное отклонение доли выживших
n = len(df[["Survived"]])
alpha_95 = 0.05
alpha_99 = 0.01

In [20]:
from scipy.stats import t

t.interval(1 - alpha_95, n - 1, loc=mean, scale=std / np.sqrt(n)) # Доля выживших с вероятностью 95% составляет от 0.352 до 0.416

(array([0.3518446]), array([0.41583217]))

In [21]:
t.interval(1 - alpha_99, n - 1, loc=mean, scale=std / np.sqrt(n)) # Доля выживших с вероятностью 99% составляет от 0.342 до 0.426

(array([0.34175837]), array([0.4259184]))

Для женщин

In [22]:
df_f = df[df["Sex"] == "female"]
mean_f = df_f[["Survived"]].mean() #доля выживших - "среднее"
std_f = df_f[["Survived"]].std() #стандартное отклонение доли выживших
n_f = len(df_f[["Survived"]])

In [23]:
t.interval(1 - alpha_95, n - 1, loc=mean_f, scale=std_f / np.sqrt(n_f)) # Доля выживших женщин с вероятностью 95% составляет от 0.694 до 0.791

(array([0.69350291]), array([0.79057352]))

In [24]:
t.interval(1 - alpha_99, n - 1, loc=mean_f, scale=std_f / np.sqrt(n_f)) # Доля выживших с вероятностью 99% составляет от 0.678 до 0.806

(array([0.67820187]), array([0.80587456]))

Для людей с каютами первого класса

In [25]:
df_pc = df[df["Pclass"] == 1]
mean_pc = df_pc[["Survived"]].mean() #доля выживших - "среднее"
std_pc = df_pc[["Survived"]].std() #стандартное отклонение доли выживших
n_pc = len(df_pc[["Survived"]])

In [26]:
t.interval(1 - alpha_95, n - 1, loc=mean_pc, scale=std_pc / np.sqrt(n_pc)) # Доля выживших пассажиров первого класса с вероятностью 95% составляет от 0.565 до 0.694

(array([0.56499272]), array([0.69426654]))

In [27]:
t.interval(1 - alpha_99, n - 1, loc=mean_pc, scale=std_pc / np.sqrt(n_pc)) # Доля выживших пассажиров первого класса с вероятностью 99% составляет от 0.545 до 0.715

(array([0.54461556]), array([0.7146437]))

##### Ответы на вопросы:

1. В данной задаче нужно использовать вариант оценки доверительных интервалов, когда настоящая дисперсия неизвестна, так как мы имеем дело с выборкой и не знаем параметров генеральной совокупности.
2. Для данной задачи критична ошибка I рода, мы ее фиксируем на определенном уровне (например, 5% или 1%) и закладываем в расчет доверительного интервала. Чем меньше мы закладываем ошибку I рода, тем шире получаются границы доверительного интервала (соответственно растет вероятность ошибки II рода).

### Normal
Проверить гипотезу о том, что женщины выживают чаще мужчин с уровнем значимости 0.05.

Проверить гипотезу о том, что дети выживают чаще, чем взрослые.


Женщины vs мужчины

In [29]:
df_sex = df[["Sex", "Survived"]].dropna(axis=0, how='any')

fs = len(df_sex[(df_sex["Sex"] == "female") & (df_sex["Survived"] == 1)]) # число выживших женщин
f = len(df_sex[df_sex["Sex"] == "female"]) # число женщин на борту
ms = len(df_sex[(df_sex["Sex"] == "male") & (df_sex["Survived"] == 1)]) # число выживших мужчин
m = len(df_sex[df_sex["Sex"] == "male"]) # число мужчин на борту

In [30]:
count = np.array([fs, ms])
nobs = np.array([f, m])
stat, pval = proportions_ztest(count, nobs, alternative='larger') # расчет Z-статистики для сравнения двух выборочных долей
print('{0:0.3f}'.format(pval))

0.000


Значение p-value ниже уровня значимости 0.05, следовательно мы отвергаем нулевую гипотезу о равенстве долей. Доля выживших женщин статистически значимо выше, чем доля выживших мужчин.

Дети vs взрослые

In [31]:
df_age = df[["Age", "Survived"]].dropna(axis=0, how='any')
df_age["age_category"] = df_age["Age"].apply(lambda x: "child" if x < 18 else "adult")

chs = len(df_age[(df_age["age_category"] == "child") & (df_age["Survived"] == 1)]) # число выживших детей
ch = len(df_age[df_age["age_category"] == "child"]) # число детей на борту
ads = len(df_age[(df_age["age_category"] == "adult") & (df_age["Survived"] == 1)]) # число выживших взрослых
ad = len(df_age[df_age["age_category"] == "adult"]) # число взрослых на борту

count = np.array([chs, ads])
nobs = np.array([ch, ad])
stat, pval = proportions_ztest(count, nobs, alternative='larger') # расчет Z-статистики для сравнения двух выборочных долей
print('{0:0.3f}'.format(pval))

0.001


Значение p-value ниже уровня значимости 0.05, следовательно мы отвергаем нулевую гипотезу о равенстве долей. Доля выживших детей статистически значимо выше, чем доля выживших взрослых.

### Hard
Одной из важнейших тем в статистике является множественная проверка гипотез.

Если нужно много раз проверять гипотезы, то вероятность совершить ошибку первого рода будет расти с каждой новой гипотезой.

Прочитать подробнее можно здесь

Задача:

Мы отобрали 1000 человек, которые заявляют, что они экстрасенсы. Мы хотим проверить это. Для этого проводится следующий эксперимент. Перед каждым участником выкладывают 10 карт рубашкой вверх и просят угадать цвет карты (красный или черный). На уровне значимости 0.01 мы хотим быть уверены, является ли человек экстрасенсом.

Нужно смоделировать ситуацию двумя способами (предполагаем, что экстрасенсов не существует и решения участников представляют из себя биномиальное распределение):

без множественной проверки гипотез, выявить количество экстрасенсов
с множественной проверкой гипотез, используя поправку Бонферрони (правило FWER)
Сколько экстрасенсов получилось поймать в каждом из случаев?

In [32]:
from scipy.stats import binomtest

1. Дизайн без множественных сравнений: ставим 1000 экспериментов, для каждого испытуемого "экстрасенса" генерируется новая раскладка карт. Статистический вывод делаем, просто сравнивая p-value, полученное в эксперименте, и пороговое значение р = 0.01.
2. Дизайн c множественными сравнениями: ставим 1000 экспериментов, для каждого испытуемого "экстрасенса" генерируется новая раскладка карт. Статистический вывод делаем, сравнивая p-value, полученное в эксперименте, со скорректированным пороговым значением. Скорректированное значение р = alpha/m, где m - число проведенных сравнений на выборках из одной генеральной совокупности. В нашем случае порог будет 0.01/1000 = 0.00001.

In [55]:
p = 0.5
pvalue_arr = []
for i in range (0, 1000):
    s_test = np.random.binomial(1, p, 10)
    s_answ = np.random.binomial(1, p, 10)
    s_sovp = s_test==s_answ
    U = np.count_nonzero(s_sovp)
    result = binomtest(U, 10, p, alternative='greater')
    pvalue_arr.append(result.pvalue)
    
Extrasense = np.array(pvalue_arr)
Extrasense_yes = Extrasense[Extrasense < 0.01].size
Extrasense_yes_B = Extrasense[Extrasense < 0.00001].size
print(Extrasense_yes, Extrasense_yes_B, sep=' и ', end=' ')
print(" экстрасенса в первом и втором экспериментах, соответственно")

3 и 0  экстрасенса в первом и втором экспериментах, соответственно


Без поправки на множественность сравнений мы сделали ложное открытие, что экстрасенсы существуют!